course_Website/blog/urls.py
from django.urls import path, include
from .views import BlogView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from .forms import BlogForm
# from .views import 

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),
    path('<page>', BlogView.as_view(), name='index'),
    path('<category>/<page>', BlogView.as_view(), name='category'),
    path('detail/<slug>/', BlogDetailView.as_view(), name='detail'),
]

course_Website/course/urls.py
from django.urls import path
from .views import update, DeleteView, CourseFormView

app_name = 'course'

urlpatterns = [
    path('create/', CourseFormView.as_view(template_name= 'course/create.html', mode='create'), name='course_create'),
    path('update/<slug>/', CourseFormView.as_view(template_name='course/update.html', mode='update'), name='course_edit'),
    path('delete/<courseId>', DeleteView.as_view(), name='course_delete')
]

course_Website/course_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('course/', include('course.urls', namespace='course')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('authApp.urls', namespace='auth'))
]

course_Website/main/urls.py
from django.urls import path, include
from .views import DashboardView, About, CategoryView

app_name = 'main'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    path('course/', include('course.urls', namespace='course')),
]

course_Website/main/models.py
from django.db import models

# Create your models here.

course_Website/main/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from course.models import Course
from django.views.generic.base import TemplateView, RedirectView
# Create your views here.

# * FUNCTION BASE
# def dashboard(request):
#     categories = Course.objects.values('category').distinct()
#     courses = Course.objects.values()
#     context = {
#         "courses" : courses, 
#         "categories" : categories
#     }
#     return render(request, 'index.html', context)

# def category_filter(request, category):
#      categories = Course.objects.values('category').distinct()
#      courses = Course.objects.filter(category=category)
#      context = {
#         "courses" : courses, 
#         "categories" : categories
#     }
#      return render(request, 'index.html' ,context)


class CourseFilter:
    def course_filter(self, content):
        if len(content) == 0:
            return Course.objects.all()
        elif 'category' in content:
            # return get_object_or_404(Course, category=content.get('category'))
            return Course.objects.filter(category__iexact=content.get('category'))
        else:
            print('unknown')
            return Course.objects.none()
        

# * TEMPLATE VIEW 
class DashboardView(CourseFilter, TemplateView):
    template_name = 'index.html'
    def get_context_data(self):
            categories = Course.objects.values('category').distinct()
            # courses = Course.objects.values()
            courses = self.course_filter(self.request.GET)
            context = {
                "courses" : courses, 
                "categories" : categories
            }
            return context


 
class CategoryView(RedirectView):
    pattern_name = 'main:home'
    
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
         return super().get_redirect_url(*args, **kwargs)
 
class About(TemplateView):
    template_name = 'about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "About Us"
        context["description"] = "This is a demo website to test a django project for creating a Course App Project"
        return context

course_Website/main/templates/about.html
{% extends 'snippet/base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}
    

{% block content %}
    <div class="text-center w-100">
        <h3>{{  title }}</h3>
        <p>{{ description }}</p>
    </div>
{% endblock content %}
    

course_Website/main/templates/index.html
{% extends 'snippet/base.html' %}


{% block title %}
    Dashboard
{% endblock title %}
    

{% block content %}

<a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'course:course_create' %}">
    + Add New Course
  </a>

  <h4>Filter The Course</h4>
  <div class="d-flex w-100 justify-content-start align-items-start gap-3">
    <a href="{% url 'main:home' %}" class="btn btn-outline-primary">
      All
    </a>
    {% for c in categories %}
    <a href="{% url 'main:home' %}?category={{ c.category }}" class="btn btn-outline-primary">
      {{ c.category }}
    </a>
      {% endfor %}
  </div>

  <table class="table table-striped table=hover text-center">
    <thead class="table-dark">
      <tr>
        <th scope="col">No</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Date Created</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      
      {% for course in courses %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ course.title }}</td>
        <td>{{ course.description }}</td>
        <td>{{ course.category }}</td>
        <td>{{ course.timestamps }}</td>
        <td>
          <a href="{% url 'course:course_edit' course.slug %}" class="btn btn-outline-primary">
            Update
          </a>
          <form class="d-inline" action="{% url 'course:course_delete' course.id %}" method='POST'>
            {% csrf_token %}
            <button class="btn btn-outline-danger">
              Delete
            </button>
          </form>
        </td>
      </tr>
        {% endfor %}
          
    </tbody>
  </table>
{% endblock content %}