course_Website/blog/urls.py
from django.urls import path, include
from .views import BlogView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from .forms import BlogForm
# from .views import 

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),
    path('<page>', BlogView.as_view(), name='index'),
    path('<category>/<page>', BlogView.as_view(), name='category'),
    path('detail/<slug>/', BlogDetailView.as_view(), name='detail'),
]

course_Website/course_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('course/', include('course.urls', namespace='course')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('authApp.urls', namespace='auth'))
]

course_Website/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length = 100)
    
    def __str__(self) -> str:
        return '{}. {}'.format(self.id, self.name)

class Blog(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(
        max_length = 255,
    )
    category = models.CharField(
        max_length = 255,
        choices = (
            ('Life Style', 'Life Style'),
            ('Technology', 'Technology'),
            ('Education', 'Education'),
            ('Entertaiment', 'Entertaiment')
        ),
        default = 'Life Style',
    )
    is_published = models.BooleanField(default=False)
    description = models.TextField()
    published = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, unique=True, editable = False)
    
    class Meta:
        default_permissions = ('add', 'change', 'delete') # By default it will contains 4: add, cahnge, delete, view
        permissions = ( 
            ('publish_blog', 'Can publish blog'),
        ) # custom permissions
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        if self.is_published == True:
            self.published = timezone.now()
        super(Blog, self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return '{}. {}'.format(self.id, self.title)
    
    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

course_Website/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        # exclude = [
        #     'slug'
        # ]
        
        fields = [
            'author',
            'title',
            'category',
            'description',
            'is_published',
        ]
        
        widgets = {
            'title' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'Input the blog title ...'
                }
            ),
            'category' : forms.Select(
                attrs = {
                    'class' : 'form-control'
                }
            ),
            'author' : forms.Select(
                attrs = {
                    'class' : 'form-control'
                }
            ),
            'description' : forms.Textarea(
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'Insert the blog description ...'
                }
            ),
            'is_published' : forms.CheckboxInput(
                attrs = {
                    'class' : 'form-check-input ms-2'
                }
            )
        }

course_Website/blog/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import (
        ListView, 
        DetailView,
        FormView, 
        CreateView,
        UpdateView, 
        DeleteView
    )
from .models import Blog
from django.core.paginator import InvalidPage
from .forms import BlogForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import permission_required

# Create your views here.

class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:index', kwargs={
        'page' : 1
    })
    template_name = 'blog/blog_confirm_delete.html'

class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/update.html'
    extra_context = {
        'page_title' : 'Update Blog'
    }
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        kwargs.update(self.extra_context)
        return super().get_context_data(**kwargs)

class BlogCreateView(CreateView):
    form_class = BlogForm
    template_name = "blog/create.html"
    
    extra_context = {
        'page_title' : 'Create a New Blog'
    }
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        kwargs.update(self.extra_context)
        return super().get_context_data(**kwargs)

class BlogFormView(FormView):
    form_class = BlogForm
    template_name = 'blog/create.html'
    success_url = reverse_lazy('blog:index', kwargs = {
        'page' : 1
    })
    extra_context = {
        'page_title' : 'Create a New Blog'
    }
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        kwargs.update(self.extra_context)
        return super().get_context_data(**kwargs)
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

class BlogView(ListView):
    model = Blog
    ordering = ['title']
    paginate_by = 3
    categories = Blog.objects.values('category').distinct()
    extra_content = {
        'page_title' : 'My Blog',
        'categories' : categories
    }
    
    def get_queryset(self):
        if 'category' in self.kwargs:
            self.queryset = self.model.objects.filter(category = self.kwargs['category'])
            self.kwargs.update({
                'category' : self.kwargs['category']
            })
        return super().get_queryset()
    
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        self.kwargs.update(self.extra_content)
        kwargs = self.kwargs
        return super().get_context_data(**kwargs)

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        slug = self.kwargs.get('slug')
        blog = self.model.objects.get(slug=slug)
        other_blos = self.model.objects.exclude(slug=slug)
        extra_content = {
            'page_title' : blog.title,
            'other_blogs' : other_blos
        }
        self.kwargs.update(extra_content)
        kwargs = self.kwargs
        return super().get_context_data(**kwargs)

course_Website/blog/templates/blog/blog_confirm_delete.html
{% extends 'snippet/base.html' %}


{% block content %}

    <form method="POST">
        {% csrf_token %}
        <h3>
            Are you sure want to delete this item?
        </h3>
        <div class="d-flex jsutify-content-center align-items-center gap-4 my-3">
            <input type="submit" value="confirm" class="btn btn-primary">
            <input type="submit" value="cancel" class="btn btn-outline-primary">
        </div>
    </form>

{% endblock content %}
    

course_Website/blog/templates/blog/blog_detail.html
{% extends 'snippet/base.html' %}

{% block title %}
    {{ page_title }}
{% endblock title %}


{% block content %}

{% include 'snippet/back.html' %}
 
    <h3>{{ object.title }}</h3>
    <h5>Diturlis oleh: {{ object.author.name }}</h5>
    <p>{{ object.description }}</p>

    <h3>Related Blog</h3>
    
    {% for blog in other_blogs %}
        <div class="card p-3 m-3">
            <h3 data-blog-detail-url="{% url 'blog:detail' blog.slug %}" onclick="blogHandler(this)">{{ blog.title }}</h3>
            <h5>Diturlis oleh: {{ blog.author.name }}</h5>
            <p>{{ blog.description|truncatechars:500 }}</p>
            </div>
        </div>
    {% endfor %}
        

{% endblock content %}

{% block script %}
<script>
      const blogHandler = (e) => {
        const dataUrl = e.dataset.blogDetailUrl
           window.location.href = dataUrl
      }
</script>
{% endblock script %}
    
    

course_Website/blog/templates/blog/blog_list.html
{% extends 'snippet/base.html' %}

{% block title %}
    {{ page_title }}
{% endblock title %}


{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock style %}
        

{% block content %}
    <div class="d-flex w-100 justify-content-start align-items-start gap-3">
        <a class="btn btn-outline-primary" href="/blog/1">All</a>
        {% for c in categories %}
            <a class="btn btn-outline-primary" href="{% url 'blog:category' category=c.category page=1 %}">{{ c.category }}</a>
        {% endfor %}
    </div>
        
    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'blog:create' %}">+ Create Blog</a>
    
    {% for content in object_list %}
    <div class="card p-3 m-3 w-100">
        <div class="d-flex justify-content-between align-items-center gap-5">
            <h3 data-blog-detail-url="{% url 'blog:detail' content.slug %}" onclick="blogHandler(this)">{{ content.title }}</h3>
            <div class="d-flex justify-content-center align-items-center gap-3">
                <a href="{% url 'blog:update' content.id %}" class="btn btn-outline-dark">
                    <span>
                        <i class="bi bi-pencil"></i>
                    </span>
                </a>
                <a href="{% url 'blog:delete' content.id %}" class="btn btn-outline-danger">
                    <span>
                        <i class="bi bi-trash"></i>
                    </span>
                </a>
            </div>
            {% comment %} <button data-blog-detail-url="{% url 'blog:update' content.id  %}" type="button" onclick="blogHandler(this)" class="btn btn-outline-dark">Edit</button> {% endcomment %}
        </div>
        <h5>Diturlis oleh: {{ content.author.name }}</h5>
        <p>{{ content.description|truncatechars:500 }}</p>
    </div>
    {% endfor %}

    
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:index' page_obj.previous_page_number %}">Previous</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
                <li class="page-item"><a class="page-link" href="{{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{{ page_obj.paginator.num_pages }}">Next</a></li>
            {% endif %}
        </ul>
      </nav>
      {% endif %}    
{% endblock content %}

{% block script %}
<script>
      const blogHandler = (e) => {
        const dataUrl = e.dataset.blogDetailUrl
        console.log(dataUrl)
           window.location.href = dataUrl
      }
</script>
{% endblock script %}
    
    

course_Website/blog/templates/blog/create.html
{% extends 'snippet/base.html' %}

{% block title %}
    Create Blog
{% endblock title %}

{% block content %}

{% include 'snippet/back.html' %}

    <h3>Create A New Blog</h3>
    <form class="w-100" action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="my-3">
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
            {{ field }}
            
            {% if field.errors %}
            <div class="alert alert-danger my-3">
                <ul>
                    {% for error in field.errors %}
                    <li>
                        {{ error }}        
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
                
        </div>
        {% endfor %}
        <div class="my-3">
            <button class="btn btn-outline-primary">Create</button>
        </div>
    </form>
{% endblock content %}
    

course_Website/blog/templates/blog/update.html
{% extends 'snippet/base.html' %}

{% block title %}
    {{ page_title }}
{% endblock title %}

{% block content %}

{% include 'snippet/back.html' %}

    <h3>Create A New Blog</h3>
    <form class="w-100" action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="my-3">
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
            {{ field }}
            
            {% if field.errors %}
            <div class="alert alert-danger my-3">
                <ul>
                    {% for error in field.errors %}
                    <li>
                        {{ error }}        
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
                
        </div>
        {% endfor %}
        <div class="my-3">
            <button class="btn btn-outline-primary">Create</button>
        </div>
    </form>
{% endblock content %}
    