course_Website/authApp/urls.py
from django.urls import path, include
from .views import loginView, register, logoutView

# from .views import 

app_name = 'auth'

urlpatterns = [
    # path('login/', AuthView.as_view(template_name = 'auth/login.html'), name='login'),
    # path('register/', AuthView.as_view(template_name = 'auth/register.html'), name='register')
    path('login/', loginView, name='login'),
    path('register/', register, name='register'),
    path('logout/', logoutView, name='logout')
]

course_Website/blog/urls.py
from django.urls import path, include
from .views import BlogView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from .forms import BlogForm
# from .views import 

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),
    path('<page>', BlogView.as_view(), name='index'),
    path('<category>/<page>', BlogView.as_view(), name='category'),
    path('detail/<slug>/', BlogDetailView.as_view(), name='detail'),
]

course_Website/course_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('course/', include('course.urls', namespace='course')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('authApp.urls', namespace='auth'))
]

course_Website/main/urls.py
from django.urls import path, include
from .views import DashboardView, About, CategoryView

app_name = 'main'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    path('course/', include('course.urls', namespace='course')),
]

course_Website/main/models.py
from django.db import models

# Create your models here.

course_Website/main/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from course.models import Course
from django.views.generic.base import TemplateView, RedirectView
# Create your views here.

# * FUNCTION BASE
# def dashboard(request):
#     categories = Course.objects.values('category').distinct()
#     courses = Course.objects.values()
#     context = {
#         "courses" : courses, 
#         "categories" : categories
#     }
#     return render(request, 'index.html', context)

# def category_filter(request, category):
#      categories = Course.objects.values('category').distinct()
#      courses = Course.objects.filter(category=category)
#      context = {
#         "courses" : courses, 
#         "categories" : categories
#     }
#      return render(request, 'index.html' ,context)


class CourseFilter:
    def course_filter(self, content):
        if len(content) == 0:
            return Course.objects.all()
        elif 'category' in content:
            # return get_object_or_404(Course, category=content.get('category'))
            return Course.objects.filter(category__iexact=content.get('category'))
        else:
            print('unknown')
            return Course.objects.none()
        

# * TEMPLATE VIEW 
class DashboardView(CourseFilter, TemplateView):
    template_name = 'index.html'
    def get_context_data(self):
            categories = Course.objects.values('category').distinct()
            # courses = Course.objects.values()
            courses = self.course_filter(self.request.GET)
            context = {
                "courses" : courses, 
                "categories" : categories
            }
            return context


 
class CategoryView(RedirectView):
    pattern_name = 'main:home'
    
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
         return super().get_redirect_url(*args, **kwargs)
 
class About(TemplateView):
    template_name = 'about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "About Us"
        context["description"] = "This is a demo website to test a django project for creating a Course App Project"
        return context

course_Website/main/templates/snippet/back.html
<div class="my-3">
    <button type="button" onclick="history.back()" class="btn btn-outline-primary"> Back</button>
</div>

course_Website/main/templates/snippet/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %} | My Course</title>
    {% comment %} bootstrap link {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block style %} {% endblock style %}
  </head>
  <body>
    {% include 'snippet/header.html' %}

    <main class="container w-100 d-flex justify-content-center align-items-start flex-column gap-3" style="min-height: 100vh;">
      {% block content %} {% endblock content %}
    </main>

    {% include 'snippet/footer.html' %}

    
    {% block script %} {% endblock script %}
  </body>
</html>

course_Website/main/templates/snippet/footer.html
<footer class="w-100 bg-dark text-center p-3 text-white">
    <h6>Created By : Dimas Dani Zaini</h6>
</footer>

course_Website/main/templates/snippet/header.html
<header class="navbar navbar-expand-lg bg-dark stick-top mb-4"  data-bs-theme="dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:home' %}">My Course</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between align-items-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'main:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'main:about' %}">About</a>
          </li>
        </ul>
        <div class="d-flex justify-content-center align-items-center gap-4">
          <a href="{% url 'auth:login' %}" class="btn btn-outline-light">
            Login
          </a>
          <a href="{% url 'auth:register' %}" class="btn btn-outline-light">
            Register
          </a>
          <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user }}
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>